version: '3'
services:
  rocm_pytorch:
    image: rocm/pytorch:latest
    container_name: learned_index
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
    ipc: host
    shm_size: 8G
    volumes:
      - /home/yulab/project/learned_index:/learned_index
